# Site
title: Cinthia Mendonça

# URL
url: https://cinthia.ml
baseurl: ''
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4664

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      cover: "/assets/covers/homecover.jpg"

# Data
social:
  facebook_url: "https://www.facebook.com/CinthiaMendonca"
  twitter_url: "https://twitter.com/haikaio"
  twitter_user: "@haikaio"

# prose.io
prose:
  media: 'assets/posts'
  ignore:
    - .gitignore
    - _config.yml
    - _includes
    - _layouts
    - _pages/404.md
    - _pages/index.md
    - _sass
    - css
    - js
    - CNAME
    - assets/favicons
    - assets/swipebox
    - assets/covers
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "nome do projeto"
          placeholder: "Colocar Aqui o Nome Do Projeto"
      - name: "swipebox"
        field:
          element: "text"
          label: "prefixo dos arquivos de imagem para serem incluidos na galeria"
          placeholder: "p1_"
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "menu"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "nome da página"
          placeholder: "Colocar Aqui o Nome Da Página"
      - name: "permalink"
        field:
          element: "text"
          label: "link dessa página"
          placeholder: "/contato/"
